name: Run Rive tests

on:
  pull_request:
    branches:
      - main
  push:

jobs:
  run_tests:
    name: Run Rive tests
    runs-on: ghcr.io/cirruslabs/macos-runner:sonoma
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_GITHUB }}
          submodules: true

      - name: Configure venv
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
      - name: Installing pre-requisites
        run: |
          set -x
          # Install some dependencies & premake5
          brew install ninja
          curl https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-macosx.tar.gz -L -o premake_macosx.tar.gz
          tar -xvf premake_macosx.tar.gz 2>/dev/null
          rm premake_macosx.tar.gz
          sudo chmod a+x premake5
          mkdir bin
          cp premake5 bin/premake5
          sudo mv premake5 /usr/local/bin
          pip3 install ply

      - name: Build everything (using the cache, we should make an archive of course)
        run: |
          ./scripts/build.sh ios_sim release

      - name: Testing iOS app
        run: ./scripts/test.sh
